on: push

apiVersion: 1.0.0
location: "france central"
name: livenesstest
properties:
  containers:
    - name: 20180417
      properties:
        image: efreidevops.azurecr.io/20180417:v1
        resources:
          requests:
            cpu: 1.0
            memoryInGB: 1.5
        livenessProbe:
          httpGet:
            path: http://devops-20180417.francecentral.azurecontainer.io/echo?lat=9.32&lon=102.75
          periodSeconds: 5
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
      - protocol: http
        port: "80"
tags: null
type: Microsoft.ContainerInstance/containerGroups
